// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCapiEbqsL6iLrOQRTfDIrKOluErMjHsAs',
    appId: '1:224508527308:web:a1ef5304efd46d524d7869',
    messagingSenderId: '224508527308',
    projectId: 'sewa-tool-camp',
    authDomain: 'sewa-tool-camp.firebaseapp.com',
    storageBucket: 'sewa-tool-camp.appspot.com',
    measurementId: 'G-W0RH3NYV6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOvRTOxkcNIIrl0RtdRdAbqiZqJ5yc7t8',
    appId: '1:224508527308:android:dc02421bc60337ce4d7869',
    messagingSenderId: '224508527308',
    projectId: 'sewa-tool-camp',
    storageBucket: 'sewa-tool-camp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB305f56imh2nufGxinSIENAUwq2VCaDgk',
    appId: '1:224508527308:ios:63d17f724531366f4d7869',
    messagingSenderId: '224508527308',
    projectId: 'sewa-tool-camp',
    storageBucket: 'sewa-tool-camp.appspot.com',
    iosBundleId: 'com.exa',
  );

}